[build-system]
requires = [
    "scikit-build-core",
    "pybind11[global]>=2.13.6",
    "cmake",
    "ninja",  # optional but faster builds
]
build-backend = "scikit_build_core.build"

[project]
name = "redqueen"
version = "0.1.0"
description = "Simple C++ bindings to the Red Queen Genetic Algorithm library."
authors = [ { name = "Mack Preston", email = "mack.preston42@gmail.com"}]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">3.7"

[tool.scikit-build]
build-dir = "build"
wheel.packages = []
build.verbose = true

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
test-extras = ["test"]
test-skip = ["*universal2:arm64"]
build-verbosity = 1

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = [
    "B",   # flake8-bugbear
    "I",   # isort
    "PGH", # pygrep-hooks
    "RUF", # Ruff-specific
    "UP",  # pyupgrade
]