// A real mid-game Checkers position -- generated by games.checkers itself (two random strategies,
// seed 4, 22 plies via play-style reset()/step()), not hand-drawn. Used as the Checkers card's
// art until the game has a playable UI (docs/design/0006 phases 2-4).
import type { GridCell } from "~/types/games"

export const checkersSnapshot: { width: number; height: number; cells: GridCell[] } = {
  width: 8,
  height: 8,
  cells: [{"x": 5, "y": 0, "label": "black_king"}, {"x": 7, "y": 0, "label": "red_man"}, {"x": 4, "y": 1, "label": "red_man"}, {"x": 1, "y": 2, "label": "red_man"}, {"x": 3, "y": 2, "label": "red_man"}, {"x": 1, "y": 4, "label": "black_man"}, {"x": 5, "y": 4, "label": "black_man"}, {"x": 4, "y": 5, "label": "black_man"}, {"x": 1, "y": 6, "label": "black_man"}, {"x": 7, "y": 6, "label": "black_man"}, {"x": 0, "y": 7, "label": "black_man"}, {"x": 2, "y": 7, "label": "black_man"}, {"x": 4, "y": 7, "label": "black_man"}, {"x": 6, "y": 7, "label": "black_man"}],
}
