"""Build the game core for the browser: rust/wasm -> apps/frontend/app/wasm/games/ (docs/design/0009).

The output is checked in, so running the frontend never needs a Rust toolchain; this script is how it
is regenerated after any change under rust/. It also records a hash of the Rust sources it was built
from (`source-hash.txt`), and `tests/test_wasm_build.py` fails if the sources change without a rebuild
-- a stale browser build would silently play a different game than training does.

Needs: cargo, the wasm32-unknown-unknown target, and wasm-bindgen-cli matching rust/wasm's
wasm-bindgen version (`cargo install wasm-bindgen-cli --version <it> --locked`).

Run from anywhere: uv run python libs/games/build-wasm.py
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "apps" / "frontend" / "app" / "wasm" / "games"
TARGET = "wasm32-unknown-unknown"
PROFILE = "wasm-release"


def source_hash() -> str:
    """sha256 over every Rust source and manifest that goes into the WASM build, in a stable order."""
    digest = hashlib.sha256()
    files = sorted(
        [HERE / "Cargo.toml", HERE / "Cargo.lock", *HERE.glob("rust/core/**/*"), *HERE.glob("rust/wasm/**/*")],
        key=lambda p: p.relative_to(HERE).as_posix(),
    )
    for path in files:
        if path.is_file() and "target" not in path.parts:
            digest.update(path.relative_to(HERE).as_posix().encode())
            digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
    return digest.hexdigest()


def main() -> None:
    subprocess.run(
        ["cargo", "build", "-p", "games-wasm", "--target", TARGET, "--profile", PROFILE], cwd=HERE, check=True
    )
    wasm = HERE / "target" / TARGET / PROFILE / "games_wasm.wasm"
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    subprocess.run(
        [
            "wasm-bindgen",
            str(wasm),
            "--out-dir",
            str(OUT),
            "--out-name",
            "games",
            "--target",
            "web",
            "--omit-default-module-path",
        ],
        check=True,
    )
    (OUT / "source-hash.txt").write_text(source_hash() + "\n", encoding="utf-8")
    (OUT / "README.md").write_text(
        "Generated by `libs/games/build-wasm.py` from `libs/games/rust/wasm` -- don't edit; rebuild.\n",
        encoding="utf-8",
    )
    size = (OUT / "games_bg.wasm").stat().st_size
    print(f"wrote {OUT} ({size:,} bytes of wasm)")


if __name__ == "__main__":
    sys.exit(main())
