/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games/{game}/interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interfaces
         * @description The representations (observer + action adapter) a model can be trained under for `game`.
         */
        get: operations["get_interfaces_games__game__interfaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Every evaluation of `game` (optionally one protocol), best mean score first. Records from
         *     different protocols aren't comparable -- a client showing more than one groups by protocol.
         */
        get: operations["get_leaderboard_games__game__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Published packages for `game`, per leaderboard entrant, plus `base_url` -- where `blobs/<sha>`
         *     and `manifests/<id>.json` are fetched from. Empty (not 404) for a game with nothing published.
         */
        get: operations["get_catalog_games__game__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blob */
        get: operations["get_blob_models_blobs__sha256__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/manifests/{package_id}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_models_manifests__package_id__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/artifacts/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_runs__run_id__artifacts__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/artifacts/{ref}/brain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Brain
         * @description A champion as plain numbers a game core can be built from (`evolve.networks.compiled`): a layered
         *     network's weights, or a NEAT genome's compiled evaluation plan. What the browser feeds the Rust
         *     `CheckersStrategy` -- so no client re-implements NEAT or the weight layout.
         */
        get: operations["get_brain_runs__run_id__artifacts__ref__brain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/artifacts/{ref}/package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Champion
         * @description Package any stored champion on demand -- how the browser watches a champion that was never
         *     published (a still-training run's latest, a pinned generation). Development/live-training only:
         *     it costs a little server compute per *new* champion, never per frame, and packages are
         *     content-addressed, so asking again for the same champion re-uses the stored one. Unlike
         *     jobs/publish_models.py it measures only numeric parity (on random inputs), not action agreement
         *     on the protocol's games -- so it's marked `on_demand`, and never becomes a leaderboard entrant.
         */
        post: operations["export_champion_runs__run_id__artifacts__ref__package_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control Run */
        post: operations["control_run_runs__run_id__control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics History */
        get: operations["get_metrics_history_runs__run_id__metrics_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/metrics/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Metrics */
        get: operations["stream_metrics_runs__run_id__metrics_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ControlAction
         * @enum {string}
         */
        ControlAction: "pause" | "resume" | "step";
        /** ControlRequest */
        ControlRequest: {
            /** @description Control action to apply to a running evolve() call. */
            action: components["schemas"]["ControlAction"];
        };
        /** EvaluationRecord */
        EvaluationRecord: {
            /** Champion Ref */
            champion_ref?: string | null;
            /** Created At */
            created_at: number;
            /**
             * Entrant Id
             * @description Stable id, e.g. 'run:<run_id>' or 'baseline:greedy'.
             */
            entrant_id: string;
            /**
             * Entrant Kind
             * @enum {string}
             */
            entrant_kind: "champion" | "baseline" | "human";
            /** Game */
            game: string;
            /** Hardware */
            hardware?: {
                [key: string]: unknown;
            };
            /**
             * Interface
             * @description Interface id the entrant played under (docs/design/0007).
             */
            interface: string;
            /**
             * Label
             * @description Human-readable entrant name.
             */
            label: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /**
             * Protocol
             * @description Versioned evaluation protocol, e.g. 'snake.score.v1'.
             */
            protocol: string;
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * GenerationStats
         * @description Per-generation summary stats for one run (and, if using islands, one island).
         */
        GenerationStats: {
            /**
             * Best Fitness
             * @description Fitness of the best individual in this generation.
             */
            best_fitness: number;
            /**
             * Champion Ref
             * @description ArtifactStore key for this generation's best individual's stored program.
             */
            champion_ref: string;
            /**
             * Diversity
             * @description Population diversity metric for this generation (higher = more diverse).
             */
            diversity: number;
            /**
             * Extras
             * @description Algorithm-specific numbers for this generation, free-form (e.g. NEAT's species count and its champion's structure size). None for algorithms with nothing extra to say. Kept generic on purpose so a new algorithm needs no telemetry schema change.
             */
            extras?: {
                [key: string]: number;
            } | null;
            /**
             * Generation
             * @description 0-indexed generation number within the run.
             */
            generation: number;
            /**
             * Held Out Score
             * @description The champion's mean *game score* on games it never trained on, if the job measured it this generation (usually every N generations -- None otherwise). Monitoring only, never used for selection: it's what shows overfitting, i.e. training fitness rising while this falls (docs/design/0007).
             */
            held_out_score?: number | null;
            /**
             * Island Id
             * @description Island id, if the run uses an island model; None for a single population.
             */
            island_id?: string | null;
            /**
             * Mean Fitness
             * @description Mean fitness across the generation's population.
             */
            mean_fitness: number;
            /**
             * Run Id
             * @description Registry-assigned id of the run this generation belongs to.
             */
            run_id: string;
            /**
             * Timestamp
             * @description Unix timestamp when this generation's stats were recorded.
             */
            timestamp: number;
            /**
             * Worst Fitness
             * @description Fitness of the worst individual in this generation.
             */
            worst_fitness: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RunInfo
         * @description Metadata for one evolution run, as stored in the RunRegistry.
         */
        RunInfo: {
            /**
             * Config
             * @description Run configuration/hyperparameters as provided at creation.
             */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Unix timestamp when the run was created.
             */
            created_at: number;
            /**
             * Run Id
             * @description Unique id for this run, assigned at creation.
             */
            run_id: string;
            /**
             * Status
             * @description Current lifecycle status of the run.
             * @enum {string}
             */
            status: "running" | "paused" | "completed" | "failed";
            /**
             * Summary
             * @description Final summary metrics once the run completes, if set.
             */
            summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Updated At
             * @description Unix timestamp of the last status/summary update.
             */
            updated_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_interfaces_games__game__interfaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_games__game__leaderboard_get: {
        parameters: {
            query?: {
                protocol?: string | null;
            };
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_games__game__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_blob_models_blobs__sha256__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_models_manifests__package_id__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"][];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_runs__run_id__artifacts__ref__get: {
        parameters: {
            query?: {
                kind?: "program" | "trace";
            };
            header?: never;
            path: {
                run_id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brain_runs__run_id__artifacts__ref__brain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_champion_runs__run_id__artifacts__ref__package_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_run_runs__run_id__control_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_history_runs__run_id__metrics_history_get: {
        parameters: {
            query?: {
                since_generation?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_metrics_runs__run_id__metrics_stream_get: {
        parameters: {
            query?: {
                since_generation?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
