/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_checkersgame_free: (a: number, b: number) => void;
export const __wbg_randompolicy_free: (a: number, b: number) => void;
export const __wbg_reach1dgame_free: (a: number, b: number) => void;
export const __wbg_snakegame_free: (a: number, b: number) => void;
export const checkersgame_cells: (a: number) => [number, number];
export const checkersgame_currentPlayer: (a: number) => number;
export const checkersgame_done: (a: number) => number;
export const checkersgame_legalMoves: (a: number) => [number, number];
export const checkersgame_new: (a: number) => number;
export const checkersgame_observation: (a: number) => [number, number];
export const checkersgame_reset: (a: number) => void;
export const checkersgame_simulate: (a: number, b: number) => [number, number, number, number];
export const checkersgame_step: (a: number, b: number) => [number, number, number];
export const checkersgame_winner: (a: number) => number;
export const decodeRelative3: (a: number, b: number) => number;
export const greedyDecide: (a: number, b: number) => number;
export const randompolicy_decide: (a: number, b: number, c: number) => number;
export const randompolicy_new: (a: number) => number;
export const reach1dgame_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const reach1dgame_observation: (a: number) => [number, number];
export const reach1dgame_position: (a: number) => number;
export const reach1dgame_reset: (a: number) => void;
export const reach1dgame_step: (a: number, b: number) => number;
export const snakegame_cells: (a: number) => [number, number];
export const snakegame_done: (a: number) => number;
export const snakegame_height: (a: number) => number;
export const snakegame_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const snakegame_observation: (a: number) => [number, number];
export const snakegame_reset: (a: number) => void;
export const snakegame_score: (a: number) => number;
export const snakegame_step: (a: number, b: number) => number;
export const snakegame_width: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
