"""Write one population-based training run's history (jobs/checkers_pbt_run.py's `<run_id>-population` artifact) as a
frontend data file, for the "Who to Play" chapter's figure: every member's round-robin score and settings each
generation, and who copied whom (docs/design/0014).

  uv run python jobs/export_pbt_history.py [--experiment selfplay-v4] [--arm g-pbt] [--seed 0]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from run_context import TelemetryStores

OUT = Path(__file__).resolve().parents[1] / "apps" / "frontend" / "app" / "data" / "pbtHistory.ts"


def main(experiment: str = "selfplay-v4", arm: str = "g-pbt", seed: int = 0) -> None:
    registry, _, artifacts = TelemetryStores.open()
    (run,) = [
        r
        for r in registry.list_runs()
        if r.config.get("experiment") == experiment
        and r.config.get("arm") == arm
        and r.config.get("rng_seed") == seed
        and r.status == "completed"
    ]
    log = json.loads(artifacts.get_program(f"{run.run_id}-population").decode("utf-8"))
    generations = [
        {
            "scores": [round(s, 3) for s in g["scores"]],
            # rounded for the page: the figure draws them, nothing recomputes from them
            "settings": [{k: round(v, 5) for k, v in s.items()} for s in g["settings"]],
            "copied": [list(pair) for pair in g["copied"]],
        }
        for g in log
    ]
    initial = [{k: round(v, 5) for k, v in s.items()} for s in run.config["initial_settings"]]
    OUT.write_text(
        "// Generated by jobs/export_pbt_history.py -- do not edit. One population-based training run (docs/design/0014):\n"
        f"// {experiment} / {arm} / seed {seed}, run {run.run_id[:8]}. `generations[g].scores` are each member's points per\n"
        "// game in that round robin; `settings` are what each member trains with *after* the round (exploit/explore\n"
        "// applied); `copied` lists [loser, winner] pairs; `initial` is every member's sampled starting settings.\n\n"
        "export interface PbtSettings {\n  learning_rate: number\n  lambda: number\n  pool_fraction: number\n  pfsp: number\n}\n\n"
        "export interface PbtGeneration {\n  scores: number[]\n  settings: PbtSettings[]\n  copied: [number, number][]\n}\n\n"
        f"export const PBT_RUN = {json.dumps(run.run_id[:8])}\n"
        f"export const PBT_INTERVAL = {int(run.config['interval'])}\n"
        f"export const initial: PbtSettings[] = {json.dumps(initial)}\n"
        f"export const generations: PbtGeneration[] = {json.dumps(generations)}\n",
        encoding="utf-8",
    )
    print(f"wrote {len(generations)} generations of {len(initial)} members to {OUT}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export a PBT run's population history for the frontend.")
    parser.add_argument("--experiment", default="selfplay-v4")
    parser.add_argument("--arm", default="g-pbt")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    main(args.experiment, args.arm, args.seed)
