"""Write the Checkers ballot (games.checkers_openings, docs/design/0013) as a frontend data file, for the "Measuring
Strength" chapter: every position three plies from the start, its moves, its board, and material search's verdict --
the 174 level ones are the ballot. Generated, not hand-written; re-run if the ballot's definition changes (its test
pins a digest, so it can't change silently).

  uv run python jobs/export_ballot.py
"""

from __future__ import annotations

import json
from pathlib import Path

from games.checkers import Checkers
from games.checkers_openings import BALLOT_DEPTH, BALLOT_PLIES, all_openings, ballot, level_value

OUT = Path(__file__).resolve().parents[1] / "apps" / "frontend" / "app" / "data" / "checkersBallot.ts"
CODES = {"red_man": "r", "red_king": "R", "black_man": "b", "black_king": "B"}


def _name(square) -> str:
    x, y = square
    return f"{'abcdefgh'[x]}{y + 1}"


def describe(opening: tuple[int, ...]) -> dict:
    env = Checkers()
    moves = []
    for index in opening:
        move = env.legal_moves()[index]
        moves.append(("x" if abs(move[1][0] - move[0][0]) == 2 else "-").join(_name(s) for s in move))
        env.step(move)
    labels = env.render_state()["cells"]
    # the 32 playable squares, row by row from Red's side: r/R a red man/king, b/B black, . empty
    board = "".join(CODES.get(labels.get((x, y)), ".") for y in range(8) for x in range(8) if (x + y) % 2 == 1)
    return {"moves": moves, "board": board, "value": level_value(opening, BALLOT_DEPTH)}


def main() -> None:
    chosen = set(ballot())
    rows = [{**describe(o), "ballot": o in chosen} for o in all_openings(BALLOT_PLIES)]
    body = ",\n".join("  " + json.dumps(r, separators=(",", ":")) for r in rows)
    OUT.write_text(
        "// Generated by jobs/export_ballot.py -- do not edit. Every Checkers position three plies from the start\n"
        f"// ({len(rows)}), its moves, its board, and {BALLOT_DEPTH}-ply material search's value for the side to move (men 1,\n"
        f"// kings 2): the {len(chosen)} it scores level are the ballot every strength measurement plays (docs/design/0013).\n"
        "// `board`: the 32 playable squares, row by row from Red's side (r/R a red man/king, b/B black, . empty).\n\n"
        "export interface BallotOpening {\n  moves: string[]\n  board: string\n  value: number\n  ballot: boolean\n}\n\n"
        f"export const BALLOT_PLIES = {BALLOT_PLIES}\nexport const BALLOT_DEPTH = {BALLOT_DEPTH}\n\n"
        f"export const openings: BallotOpening[] = [\n{body},\n]\n",
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} openings ({len(chosen)} in the ballot) to {OUT}")


if __name__ == "__main__":
    main()
