"""Build the RL core for the browser: rust/wasm -> apps/frontend/app/wasm/rl/ (docs/design/0010).

Like libs/games/build-wasm.py: the output is checked in, so the frontend never needs a Rust toolchain; the hash of
the sources it was built from (`source-hash.txt`) is checked by tests/test_rl_wasm_build.py. The hash also covers
the games core (a path dependency, compiled in) and the determinism fixture, which is copied next to the module so
the browser and Node checks read the same digests the native build is tested against.

Needs: cargo, the wasm32-unknown-unknown target, and wasm-bindgen-cli matching rust/wasm's wasm-bindgen version.

Run from anywhere: uv run python libs/rl/build-wasm.py
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
GAMES = HERE.parent / "games"
OUT = HERE.parents[1] / "apps" / "frontend" / "app" / "wasm" / "rl"
FIXTURE = HERE / "tests" / "determinism.json"
TARGET = "wasm32-unknown-unknown"
PROFILE = "wasm-release"


def source_hash() -> str:
    """sha256 over every source that goes into the WASM build (and the fixture shipped with it), in a stable order."""
    digest = hashlib.sha256()
    files = [
        HERE / "Cargo.toml",
        HERE / "Cargo.lock",
        FIXTURE,
        *HERE.glob("rust/core/**/*"),
        *HERE.glob("rust/envs/**/*"),
        *HERE.glob("rust/wasm/**/*"),
        GAMES / "rust" / "core" / "Cargo.toml",
        *GAMES.glob("rust/core/src/**/*"),
    ]
    root = HERE.parent
    for path in sorted(files, key=lambda p: p.relative_to(root).as_posix()):
        if path.is_file() and "target" not in path.parts:
            digest.update(path.relative_to(root).as_posix().encode())
            digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
    return digest.hexdigest()


def main() -> None:
    subprocess.run(["cargo", "build", "-p", "rl-wasm", "--target", TARGET, "--profile", PROFILE], cwd=HERE, check=True)
    wasm = HERE / "target" / TARGET / PROFILE / "rl_wasm.wasm"
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    subprocess.run(
        [
            "wasm-bindgen",
            str(wasm),
            "--out-dir",
            str(OUT),
            "--out-name",
            "rl",
            "--target",
            "web",
            "--omit-default-module-path",
        ],
        check=True,
    )
    shutil.copyfile(FIXTURE, OUT / "determinism.json")
    (OUT / "source-hash.txt").write_text(source_hash() + "\n", encoding="utf-8")
    (OUT / "README.md").write_text(
        "Generated by `libs/rl/build-wasm.py` from `libs/rl/rust/wasm` -- don't edit; rebuild.\n", encoding="utf-8"
    )
    size = (OUT / "rl_bg.wasm").stat().st_size
    print(f"wrote {OUT} ({size:,} bytes of wasm)")


if __name__ == "__main__":
    sys.exit(main())
